// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppwzkrzatepkrssntyuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwd3prcnphdGVwa3Jzc250eXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTQ4NjIsImV4cCI6MjA2NTgzMDg2Mn0.Wsgn_Kkc2x89snKa8sZKn6s20OHwM0g2liKuOREGFIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);